version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 3line-app
    ports:
      - "3030:3030"
    environment:
      SPRING_PROFILES_ACTIVE: "production"
#    volumes:
#      - ./data:/app/data